#!/usr/bin/env bash

source /opt/Kraken-Parallel/Kraken-Parallel.sh

log_path="/tmp/op-log"
version="v0.9-beta"
limit_parallel=10

function version(){
    echo "
#=================#
# Kraken-Parallel #
#=================#

 Version: $version
 Author: Bruno Dupim
 Project: https://github.com/brunodupim08/Kraken-Parallel.git
"
}
function usage(){
    cat /opt/Kraken-Parallel/usage.txt
    echo -e "\n"
    exit 0
}
function options_error(){    #usage error
	echo '
	Parameter error !!!
	usage:
		kp [OPTION] [FIXED-COMMAND] [FILE-LIST-COMMAND]
	
		kp [OPTION] [FILE-LIST-COMMAND]
		
	Try "kp --help" for more options.
	'
	exit 1
}
#Option.
[[ "$#" -eq "0" ]] && options_error
indf=0
while [[ "$#" -ne "0" ]]; do
    if [[ -z "$1" ]]; then
        shift
    fi
    case "${1}" in
        --version) version
            exit 0
        ;;
        -h|--help) 
            usage
        ;;
        -m|--max-parallel) #limit_parallel
            shift
            limit_parallel=${1}
            shift
        ;;
        -v|--verbose) 
            verbose=true
            shift
        ;;
        --new-log)
            new_log=true
            shift
        ;;
        --log-path) 
            shift
            log_path=${1}
            shift
        ;;
        -c) #Fixed Command
            shift
            fixed_command_input=${1}
            shift
        ;;
        -f) #Files
            shift
            while [[ -e "${1}" ]]; do
                if [[ ! -d "${1}" ]]; then
                    list_of_files_input[${indf}]=${1}
                    ((indf++))
                fi
                shift
            done
        ;;
        *)
            options_error
        ;;
    esac
done
[[ ! -n "${list_of_files_input[@]}" ]] && options_error || tentacles
