#!/usr/bin/env bash

source Kraken-Parallel.sh

log_path="/tmp"
version="v1.0.0"
#usage="$PWD/usage.txt"
max_parallel=10
verbose=false
new_log=false
no_log=false

#Option.
[[ "${#}" -eq "0" ]] && error_1
indf=0
while [[ "${#}" -ne "0" ]]; do
    if [[ -z "${1}" ]]; then
        shift
    fi
    case "${1}" in
        --version) 
            version
        ;;
        -h|--help) 
            usage
        ;;
        -m|--max-parallel) 
            shift
            max_parallel=${1}
            shift
        ;;
        -v|--verbose) 
            verbose=true
            shift
        ;;
        --new-log)
            new_log=true
            shift
        ;;
        --no-log) 
            shift
            no_log=true
            shift
        ;;
        --log-path) 
            shift
            log_path=${1}
            shift
        ;;
        -c) 
            shift
            fixed_command_input=${1}
            shift
        ;;
        -f) 
            shift
            while [[ -e "${1}" ]]; do
                if [[ ! -d "${1}" ]]; then
                    list_of_files_input[${indf}]=${1}
                    ((indf++))
                fi
                shift
            done
        ;;
        *)
            error_1
        ;;
    esac
done
test_options